#!/bin/bash

###
### The following block runs after commit to "master" branch
###
if [ `git rev-parse --abbrev-ref HEAD` == "master" ]; then

  # stash unsaved changes
  git stash -u

  # Layout prefix is prepended to each markdown file synced
  ###################################################################
  LAYOUT_PREFIX='---\r\nlayout: index\r\n---\r\n\r\n'

  # Switch to gh-pages branch to sync it with master
  ###################################################################
  git checkout gh-pages

  # Sync the README.md in master to index.md adding jekyll header
  ###################################################################
  git checkout master -- README.md
  mv README.md index.md
  git rm README.md

  # Sync images directory
  ###################################################################
  git checkout master -- images

  # Commit
  ###################################################################
  git add --all .
  git commit -m "Sync docs from master branch to docs gh-pages directory"

  # return to master
  git checkout master

  git stash pop

fi